dist:
  #  module: github.com/smnzlnsk/monitoring-agent
  description: Master Thesis - Telemetry driven Network Optimisation in Edge-Cloud Orchestration Frameworks
  otelcol_version: 0.109.0
  version: 0.0.1
  output_path: build
  name: agent

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.108.0

processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.108.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor v0.108.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.108.1
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.108.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.108.0
  - gomod: github.com/smnzlnsk/opentelemetry-components/exporter/mqttexporter v0.0.1
    path: exporters/mqttexporter
