dist:
  #  module: github.com/smnzlnsk/monitoring-agent
  description: Master Thesis - Telemetry driven Network Optimisation in Edge-Cloud Orchestration Frameworks
  otelcol_version: 0.109.0
  version: 0.1.0
  output_path: /tmp/monitoring-agent
  name: monitoringagent

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.109.0
  - gomod: github.com/smnzlnsk/opentelemetry-components/receiver/unixsocketreceiver v0.1.0

processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.109.0
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.109.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor v0.109.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.109.0
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.109.0
  - gomod: github.com/smnzlnsk/opentelemetry-components/exporter/mqttexporter v0.1.0
