receivers:

  hostmetrics:
    collection_interval: 5s
    #root_path: /
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      memory:
      load:
        cpu_average: true
      network:
        include:
          interfaces: veth*
          match_type: regexp

  hostmetrics/process:
    collection_interval: 5s
    scrapers:
      process:
        metrics:
          process.disk.io:
            enabled: true
        include:
          names:
            - htop
          match_type: strict
        mute_process_name_error: true


  hostmetrics/disk:
    collection_interval: 5s
    #root_path: /
    scrapers:
      disk:
      filesystem:

  unixsocket:
    polling_interval: 2s

processors:

  batch:
    timeout: 30s

  resource:
    attributes:
      - key: machine
        value: &id agent_exporter_mac
        action: upsert

  cumulativetodelta:
    include:
      metrics:
        - system.cpu.time
      match_type: strict

exporters:

  debug:
    verbosity: normal

  mqtt:
    interval: 1s
    client_id: *id
    broker:
      host: localhost
      port: 1883

service:
  telemetry:
    metrics:
      level: none
  pipelines:
    metrics:
      receivers: [unixsocket, hostmetrics, hostmetrics/process, hostmetrics/disk]
      processors: [resource, cumulativetodelta, batch]
      exporters: [debug, mqtt]
