receivers:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver
  hostmetrics:
    collection_interval: 5s
    #root_path: /
    scrapers:
      cpu:
      memory:
      load:
        cpu_average: true
      network:
      paging:
      #processes:
      #process:

  hostmetrics/disk:
    collection_interval: 60s
    #root_path: /
    scrapers:
      disk:
      filesystem:

exporters:
  debug:
    verbosity: normal
  mqttexporter:
    interval: 1s
    client_id: &id test_agent_mac
    broker:
      host: mosquitto
      port: 1883

  prometheus:
    endpoint: "localhost:8882"
    enable_open_metrics: true

  otlp:
    endpoint: monitoring-manager:4317 # TODO: configure endpoint here
    tls:
      insecure: true

processors:
  resource:
    attributes:
      - key: machine
        value: *id
        action: upsert

  cumulativetodelta:
    include:
      metrics:
        - system.cpu.time
      match_type: strict

service:
  telemetry:
    metrics:
      level: none
  pipelines:
    metrics:
      receivers: [hostmetrics, hostmetrics/disk]
      processors: [resource, cumulativetodelta]
      exporters: [debug, prometheus, mqttexporter]
