receivers:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver
  hostmetrics:
    collection_interval: 5s
    #root_path: /
    scrapers:
      cpu:
      memory:
      load:
        cpu_average: true
      network:
      #paging:
      #processes:
      #process:

  hostmetrics/disk:
    collection_interval: 60s
    #root_path: /
    scrapers:
      disk:
      filesystem:

  unixsocket:
    polling_interval: 2s


exporters:
  debug:
    verbosity: normal
  mqtt:
    interval: 1s
    client_id: &id agent_exporter_mac
    broker:
      host: localhost
      port: 1883

  prometheus:
    endpoint: "localhost:8882"
    enable_open_metrics: true

processors:
  resource:
    attributes:
      - key: machine
        value: *id
        action: upsert

  cumulativetodelta:
    include:
      metrics:
        - system.cpu.time
      match_type: strict

service:
  telemetry:
    metrics:
      level: none
  pipelines:
    metrics:
      receivers: [unixsocket,hostmetrics, hostmetrics/disk]
      processors: [resource, cumulativetodelta]
      exporters: [mqtt]
